version: "2.3"

services:
  lab:
    build:
      context: .
      dockerfile: Dockerfile
      target: lab
    container_name: jupyter_lab
    environment:
      - JUPYTER_ENABLE_LAB=yes
    ports:
    - "8888:8888"
    volumes:
    - ./programs:/home/jovyan/work/programs

  test:
    build:
      context: .
      dockerfile: Dockerfile
      target: test
    volumes:
      - .:/home/jovyan/
    entrypoint: "python -m pytest"
